spring:
  jackson:
    default-property-inclusion: NON_NULL
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
server:
  port : 8089
  error:
    include-message: always
allowedPathForPatch: /address,/address/province,/address/houseNumber,/address/street,/address/city,/address/postalCode,/emailId,/phoneNumber